# Generated by Django 2.2 on 2019-04-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('reportDate', models.DateTimeField(verbose_name='date when report is generated')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.IntegerField(default=0)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiDimEvents.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureList', models.CharField(max_length=200)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiDimEvents.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
                ('content', models.TextField(max_length=40000)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiDimEvents.Event')),
            ],
        ),
    ]
