# Generated by Django 2.2 on 2019-04-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiDimEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='searchNum',
            field=models.IntegerField(default=0),
        ),
    ]
