# Generated by Django 2.2 on 2019-04-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiDimEvents', '0003_auto_20190411_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiDimEvents.Category'),
        ),
    ]
