# Generated by Django 2.2 on 2019-04-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiDimEvents', '0004_auto_20190416_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='featureList',
            field=models.CharField(max_length=1000),
        ),
    ]
