# Generated by Django 2.2 on 2019-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiDimEvents', '0005_auto_20190417_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pv',
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.CharField(default='2019-04-23 18:43:27', max_length=100),
        ),
    ]
