# Generated by Django 2.2 on 2019-05-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiDimEvents', '0006_auto_20190424_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
            ],
        ),
    ]
