# Generated by Django 2.2 on 2019-05-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiDimEvents', '0007_hotnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotnews',
            name='eventName',
        ),
        migrations.AddField(
            model_name='hotnews',
            name='eventId',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='multiDimEvents.Event'),
            preserve_default=False,
        ),
    ]
